# ____   ____ ____   ____    ___   ______  ___    ___   __ 
# || \\ ||    || \\  || \\  // \\  | || | // \\  // \\ (( \
# ||_// ||==  ||  )) ||_// ((   ))   ||   ||=|| (( ___  \\ 
# ||    ||___ ||_//  || \\  \\_//    ||   || ||  \\_|| \_))                     
#


#A opção de de interação com o PermissionEx não foi completa, esta prevista para a v2.0.
pex: true